## 数据源配置
spring:
  datasource: # 数据库的数据配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    # url不用换行，由于数据太长了这里换行了
    url: jdbc:mysql://localhost:3306/bilibili?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123456
    https://juejin:
# https://juejin.cn/post/7076244567569203208
  redis:
    database: 0
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-idle: 16
        max-active: 32
        min-idle: 8


## mybatis 配置
mybatis:
  mapper-locations: com/example/bilibili/mapper/**/*.xml # 扫描mybatis的实现dao接口*.xml文件
## 配置服务端口
server:
  port: 8088
